server:
  port: 9060


spring:
  application:
    name: cms-server
#  数据库相关
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: yunque
    password: YunQue!2017
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      exclude: static/**,**/*Test.class,**/*Tests.class
  servlet:
    multipart:
        #请求的总文件大小
      maxRequestSize: 50MB
        #单个文件大小
      maxFileSize: 10MB
      # redis相关配置
#  redis:
#    host: 192.168.0.88
#    port: 6379
  jpa:
    open-in-view: true
#Oauth2相关
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888/users/current
    client:
      client-id: clinic-client
      client-secret: YunQue
      access-token-uri: http://localhost:8888/oauth/token
      grant-type: client_credentials, password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12345/eureka/
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
